Feature/add name to stream
jeffutter/particle-elixir pull request #2
Opened 2016-09-27 12:04 UTC by tompesman

Hi Jeffery,

I've added to name to the Stream module. So it can be referenced from the consumer. I've also added some documentation on the usage.

Cheers!

2016-09-29 17:25 UTC, jeffutter reviewed
@tompesman First off. Thanks for the PR's. I'm thrilled someone else is using this!

2016-09-29 17:27 UTC, jeffutter requested changes

2016-09-29 17:27 UTC, jeffutter commented on README.md
> +Start the workers in de `Application`.
"the `Application`"

2016-09-29 17:27 UTC, jeffutter commented on lib/particle/stream.ex
> +    GenStage.start_link(__MODULE__, url, name: __MODULE__)
Won't this make it impossible to start more than one stream at a time? Before, when passing options, you could  specify your own name, thus having multiple instances.

2016-09-30 10:22 UTC, tompesman commented on lib/particle/stream.ex
> +    GenStage.start_link(__MODULE__, url, name: __MODULE__)
You're right! I'll remove this.

2016-09-30 10:27 UTC, tompesman commented on README.md
> +Start the workers in de `Application`.
😬

2016-09-30 11:35 UTC, jeffutter approved these changes

2016-09-30 11:35 UTC, merged

2016-09-30 11:35 UTC, jeffutter commented
Nice! Thanks for the contributions. Would you like me to cut a new version on hex.pm?

2016-09-30 11:52 UTC, tompesman commented
That would be nice! 👍 Thank you!

2016-09-30 13:25 UTC, jeffutter commented
@tompesman v0.1.6 pushed